services:
    cli:
        build:
            context: .
            dockerfile: lagoon/cli.dockerfile
        image: sailonlagoon
        labels:
            lagoon.type: cli-persistent
            lagoon.persistent.name: nginx
            lagoon.persistent: /app/storage
        depends_on:
            - redis
    nginx:
        build:
            context: .
            dockerfile: lagoon/nginx.dockerfile
            args:
                CLI_IMAGE: sailonlagoon
        labels:
            lagoon.type: nginx-php-persistent
            lagoon.name: nginx
            lagoon.persistent: /app/storage
        volumes:
            - './:/app:delegated'
        depends_on:
            - cli
            - redis
    php:
        build:
            context: .
            dockerfile: lagoon/php.dockerfile
            args:
                CLI_IMAGE: sailonlagoon
        labels:
            lagoon.type: nginx-php-persistent
            lagoon.name: nginx
            lagoon.persistent: /app/storage/
        volumes:
            - './:/app:delegated'

     # SERVICE: worker
    worker:
        build:
            context: .
            dockerfile: lagoon/worker.dockerfile
            args:
                CLI_IMAGE: sailonlagoon
        labels:
            lagoon.type: worker-persistent
            lagoon.name: worker
            lagoon.persistent.name: nginx
            lagoon.persistent: /app/storage/
        

    mariadb:
        image: uselagoon/mysql-8.0
        labels:
            lagoon.type: mariadb
        environment:
            SERVICE_NAME: worker
    redis:
        build:
            context: .
            dockerfile: lagoon/redis.dockerfile
        image: uselagoon/redis-7-persistent
        labels:
            lagoon.type: redis-persistent

    mailhog:
        image: mailhog/mailhog:latest
        labels:
            lagoon.type: basic
            lagoon.service.usecomposeports: true
        ports:
            - '8025'
            - '1025'