<?php

declare(strict_types=1);

use Rector\CodingStyle\Rector\FuncCall\FunctionFirstClassCallableRector;
use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\LevelSetList;
use Rector\Set\ValueObject\SetList;
use Rector\TypeDeclaration\Rector\Property\TypedPropertyFromAssignsRector;
use Rector\TypeDeclaration\Rector\Property\TypedPropertyFromStrictSetUpRector;
use Rector\TypeDeclaration\Rector\StmtsAwareInterface\SafeDeclareStrictTypesRector;
use RectorLaravel\Rector\ClassMethod\MigrateToSimplifiedAttributeRector;
use RectorLaravel\Set\LaravelLevelSetList;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([
        __DIR__.'/app',
        __DIR__.'/bootstrap',
        __DIR__.'/config',
        __DIR__.'/database',
        __DIR__.'/public',
        __DIR__.'/resources',
        __DIR__.'/routes',
        __DIR__.'/tests',
    ]);

    // Register sets for PHP version upgrade
    $rectorConfig->sets([
        LevelSetList::UP_TO_PHP_84,
        SetList::DEAD_CODE,
        SetList::CODE_QUALITY,
        SetList::EARLY_RETURN,
        SetList::TYPE_DECLARATION,
        // WITHOUT_ATTRIBUTES: skips rewriting Eloquent scopes/casts to PHP
        // attributes — adopt that deliberately, not as a side effect
        LaravelLevelSetList::UP_TO_LARAVEL_130_WITHOUT_ATTRIBUTES,
    ]);

    // Enforces declare(strict_types=1); at the top of all files
    $rectorConfig->rule(SafeDeclareStrictTypesRector::class);

    $rectorConfig->skip([
        '**/vendor/**',
        // Generated by package discovery; contents vary per environment
        __DIR__.'/bootstrap/cache',
        // strtolower(...) narrows the callable to string params, which fails
        // phpstan max against the untyped sensitiveInputs() convention method
        FunctionFirstClassCallableRector::class => [
            __DIR__.'/app/Providers/AppServiceProvider.php',
        ],
        // Would re-type $traitObject as bare `object`, losing the
        // anonymous-class type phpstan infers from the setUp assignment
        TypedPropertyFromStrictSetUpRector::class => [
            __DIR__.'/tests/Unit/Traits/HasWebhookSensitiveDataTest.php',
        ],
        TypedPropertyFromAssignsRector::class => [
            __DIR__.'/tests/Unit/Traits/HasWebhookSensitiveDataTest.php',
        ],
        // Migrating get*Attribute() accessors to Attribute::make() drops the
        // return types larastan uses to type the magic properties (~105 new
        // phpstan errors). Legacy accessors remain fully supported; migrate
        // deliberately with typed closures if ever wanted.
        MigrateToSimplifiedAttributeRector::class,
    ]);
};
