<?php

declare(strict_types=1);

namespace App\Polydock\Apps\AmazeeClaw\Enums;

/**
 * How an AmazeeClaw-style app obtains its amazee.ai keys.
 */
enum AmazeeAiKeyMode: string
{
    /** Keys are supplied externally (e.g. MOAD) in the instance `secret`. */
    case Injected = 'injected';

    /** Keys are auto-generated per project against an anonymous backend user. */
    case Anonymous = 'anonymous';

    /** Keys are auto-generated for the claiming user, using their email. */
    case User = 'user';

    /**
     * Resolve a stored config value to a mode. Accepts the legacy `auto`/`manual`
     * values still present in existing store-app config, and defaults to Injected.
     */
    public static function fromStorage(?string $value): self
    {
        return match (strtolower(trim((string) $value))) {
            'anonymous', 'auto' => self::Anonymous,
            'user' => self::User,
            default => self::Injected, // '', 'manual', 'injected', or anything unknown
        };
    }

    /** True when the mode generates keys via the amazee.ai backend. */
    public function isAutoGenerated(): bool
    {
        return $this === self::Anonymous || $this === self::User;
    }
}
