<?php

namespace App\Polydock\Apps\Generic\Traits\Create;

use App\Models\PolydockAppInstance;
use App\Polydock\Core\PolydockAppInstanceInterface;

/**
 * Injects a LAGOON_ROUTES_JSON custom route when the store app configures one.
 *
 * Lagoon only supports ingress annotations (upload size, timeouts, etc.) on
 * custom routes, not on autogenerated ones - so apps that need them define a
 * domain pattern + annotations in app_config and we register the route as a
 * build-scoped Lagoon variable before the first deploy. The custom route
 * becomes the environment's primary route; the autogenerated route remains
 * as a fallback because the domains differ.
 */
trait InjectsLagoonCustomRouteTrait
{
    /**
     * @param  array<string, mixed>  $logContext
     */
    protected function addLagoonCustomRouteVariable(PolydockAppInstanceInterface $appInstance, string $projectName, array $logContext = []): void
    {
        $storeApp = $appInstance instanceof PolydockAppInstance ? $appInstance->storeApp : null;
        $routeConfig = $storeApp?->lagoon_custom_route_config;

        if (! $routeConfig) {
            return;
        }

        $domain = strtolower(strtr($routeConfig['domain_pattern'], [
            '{project}' => $projectName,
            '{environment}' => (string) $appInstance->getKeyValue('lagoon-deploy-branch'),
        ]));

        $routesJson = json_encode([
            'routes' => [
                [
                    'domain' => $domain,
                    'service' => $routeConfig['service'],
                    'tls-acme' => true,
                    'annotations' => (object) $routeConfig['annotations'],
                ],
            ],
        ]);

        if ($routesJson === false) {
            throw new \Exception('Failed to encode LAGOON_ROUTES_JSON payload');
        }

        $this->addOrUpdateLagoonProjectVariable($appInstance, 'LAGOON_ROUTES_JSON', base64_encode($routesJson), 'BUILD');
        $this->info('Injected LAGOON_ROUTES_JSON custom route', $logContext + ['domain' => $domain]);
    }
}
