<?php

namespace Tests\Feature;

use App\Polydock\Apps\AmazeeClaw\Enums\AmazeeAiKeyMode;
use App\Polydock\Apps\AmazeeClaw\PolydockAmazeeClawAiApp;
use App\Polydock\Core\PolydockAppInstanceInterface;
use Filament\Forms\Components\Field;
use Tests\Doubles\DoublePolydockAppInstance;
use Tests\TestCase;

class TestablePolydockAmazeeClawAiApp extends PolydockAmazeeClawAiApp
{
    /**
     * @var array<string, mixed>
     */
    public array $injectedVariables = [];

    /**
     * @var list<string>
     */
    public array $deletedVariables = [];

    #[\Override]
    public function addOrUpdateLagoonProjectVariable($appInstance, $variableName, $variableValue, $variableScope): void
    {
        $this->injectedVariables[$variableName] = $variableValue;
    }

    /** Simulates Lagoon refusing the delete (it reports errors in the payload, it does not throw). */
    public bool $deleteSucceeds = true;

    /**
     * Records the delete decision instead of reaching for the Lagoon GraphQL client.
     *
     * @param  array<string, mixed>  $logContext
     */
    #[\Override]
    protected function deleteMcpServerTokenVariable(PolydockAppInstanceInterface $appInstance, array $logContext = []): bool
    {
        $this->deletedVariables[] = self::MCP_TOKEN_VARIABLE;

        return $this->deleteSucceeds;
    }

    /**
     * @param  array<string, mixed>  $logContext
     */
    public function callEnsureMcpServerConfiguration(PolydockAppInstanceInterface $appInstance, array $logContext = []): void
    {
        $this->ensureMcpServerConfiguration($appInstance, $logContext);
    }
}

class AmazeeClawConfigTest extends TestCase
{
    /**
     * @param  array<string, mixed>  $config
     */
    private function createAppInstance(array $config = []): DoublePolydockAppInstance
    {
        $storeApp = new \stdClass;
        $storeApp->app_config = $config['app_config'] ?? [];

        return new DoublePolydockAppInstance($storeApp, $config['data'] ?? []);
    }

    public function test_form_schemas_contain_key_mode(): void
    {
        $storeSchema = PolydockAmazeeClawAiApp::getStoreAppFormSchema();
        $instanceSchema = PolydockAmazeeClawAiApp::getAppInstanceFormSchema();

        $hasKeyModeInStore = false;
        foreach ($storeSchema as $component) {
            if ($component instanceof Field && $component->getName() === 'amazeeai_key_mode') {
                $hasKeyModeInStore = true;
            }
        }

        $hasKeyModeInInstance = false;
        foreach ($instanceSchema as $component) {
            if ($component instanceof Field && $component->getName() === 'amazeeai_key_mode') {
                $hasKeyModeInInstance = true;
            }
        }

        $this->assertTrue($hasKeyModeInStore, 'Store App form schema should contain amazeeai_key_mode');
        $this->assertFalse($hasKeyModeInInstance, 'App Instance form schema should NOT contain amazeeai_key_mode');
    }

    public function test_key_mode_resolution(): void
    {
        $app = new PolydockAmazeeClawAiApp('Test App', 'Description', 'Author', 'https://example.com', 'support@example.com');

        // 1. Default fallback (legacy empty -> injected)
        $instanceDefault = $this->createAppInstance();
        $this->assertEquals(AmazeeAiKeyMode::Injected, $app->resolveAmazeeAiKeyMode($instanceDefault));

        // 2. Resolve from app_config (store app level); legacy 'auto' -> anonymous
        $instanceStoreApp = $this->createAppInstance([
            'app_config' => ['amazeeai_key_mode' => 'auto'],
        ]);
        $this->assertEquals(AmazeeAiKeyMode::Anonymous, $app->resolveAmazeeAiKeyMode($instanceStoreApp));

        // 3. Resolve from instance config; new 'user' value
        $instanceConfig = $this->createAppInstance([
            'data' => [
                'instance_config_amazeeai_key_mode' => 'user',
            ],
        ]);
        $this->assertEquals(AmazeeAiKeyMode::User, $app->resolveAmazeeAiKeyMode($instanceConfig));
    }

    public function test_key_mode_from_storage_maps_legacy_and_new_values(): void
    {
        $this->assertEquals(AmazeeAiKeyMode::Anonymous, AmazeeAiKeyMode::fromStorage('auto'));
        $this->assertEquals(AmazeeAiKeyMode::Anonymous, AmazeeAiKeyMode::fromStorage('anonymous'));
        $this->assertEquals(AmazeeAiKeyMode::Injected, AmazeeAiKeyMode::fromStorage('manual'));
        $this->assertEquals(AmazeeAiKeyMode::Injected, AmazeeAiKeyMode::fromStorage('injected'));
        $this->assertEquals(AmazeeAiKeyMode::Injected, AmazeeAiKeyMode::fromStorage(''));
        $this->assertEquals(AmazeeAiKeyMode::Injected, AmazeeAiKeyMode::fromStorage(null));
        $this->assertEquals(AmazeeAiKeyMode::User, AmazeeAiKeyMode::fromStorage('user'));

        $this->assertTrue(AmazeeAiKeyMode::Anonymous->isAutoGenerated());
        $this->assertTrue(AmazeeAiKeyMode::User->isAutoGenerated());
        $this->assertFalse(AmazeeAiKeyMode::Injected->isAutoGenerated());
    }

    public function test_injects_manual_credentials(): void
    {
        $app = new TestablePolydockAmazeeClawAiApp('Test App', 'Description', 'Author', 'https://example.com', 'support@example.com');

        $instance = $this->createAppInstance([
            'data' => [
                'instance_config_amazeeai_key_mode' => 'manual',
                'secret' => [
                    'llm_key' => 'manual-api-key',
                    'llm_url' => 'https://manual.api.url',
                    'vector_db_host' => 'manual-db-host',
                    'vector_db_user' => 'manual-db-user',
                    'vector_db_pass' => 'manual-db-pass',
                    'vector_db_name' => 'manual-db-name',
                ],
            ],
        ]);

        $envVars = $app->provisionAndInjectManualAmazeeAiCredentials($instance);

        $this->assertEquals('manual-api-key', $envVars['AMAZEEAI_API_KEY']);
        $this->assertEquals('https://manual.api.url', $envVars['AMAZEEAI_BASE_URL']);
        $this->assertEquals('manual-db-host', $envVars['AMAZEEAI_VECTOR_DB_HOST']);
        $this->assertEquals('manual-db-user', $envVars['AMAZEEAI_VECTOR_DB_USER']);
        $this->assertEquals('manual-db-pass', $envVars['AMAZEEAI_VECTOR_DB_PASS']);
        $this->assertEquals('manual-db-name', $envVars['AMAZEEAI_VECTOR_DB_NAME']);

        $this->assertEquals('manual-api-key', $app->injectedVariables['AMAZEEAI_API_KEY']);
        $this->assertEquals('https://manual.api.url', $app->injectedVariables['AMAZEEAI_BASE_URL']);
    }

    public function test_injects_auto_generated_credentials(): void
    {
        $app = new TestablePolydockAmazeeClawAiApp('Test App', 'Description', 'Author', 'https://example.com', 'support@example.com');

        $instance = $this->createAppInstance([
            'data' => [
                'instance_config_amazeeai_key_mode' => 'auto',
                'amazee-ai-generated-credentials' => json_encode([
                    'litellm_token' => 'auto-api-key',
                    'litellm_api_url' => 'https://auto.api.url',
                    'database_host' => 'auto-db-host',
                    'database_username' => 'auto-db-user',
                    'database_password' => 'auto-db-pass',
                    'database_name' => 'auto-db-name',
                ]),
            ],
        ]);

        $envVars = $app->provisionAndInjectManualAmazeeAiCredentials($instance);

        $this->assertEquals('auto-api-key', $envVars['AMAZEEAI_API_KEY']);
        $this->assertEquals('https://auto.api.url', $envVars['AMAZEEAI_BASE_URL']);
        $this->assertEquals('auto-db-host', $envVars['AMAZEEAI_VECTOR_DB_HOST']);
        $this->assertEquals('5432', $envVars['AMAZEEAI_VECTOR_DB_PORT']);
        $this->assertEquals('auto-db-user', $envVars['AMAZEEAI_VECTOR_DB_USER']);
        $this->assertEquals('auto-db-pass', $envVars['AMAZEEAI_VECTOR_DB_PASS']);
        $this->assertEquals('auto-db-name', $envVars['AMAZEEAI_VECTOR_DB_NAME']);

        $this->assertEquals('auto-api-key', $app->injectedVariables['AMAZEEAI_API_KEY']);
        $this->assertEquals('https://auto.api.url', $app->injectedVariables['AMAZEEAI_BASE_URL']);
    }

    public function test_build_claim_script_with_secure_stdin_variables(): void
    {
        $app = new TestablePolydockAmazeeClawAiApp('Test App', 'Description', 'Author', 'https://example.com', 'support@example.com');

        $claimScript = 'node claim.js';
        $envVars = [
            'AMAZEEAI_API_KEY' => 'sensitive-token-here',
            'AMAZEEAI_VECTOR_DB_PASS' => 'db-password-here',
        ];

        // Call the protected method using reflection
        $reflection = new \ReflectionClass($app);
        $method = $reflection->getMethod('buildClaimScriptWithInlineEnvironmentVariables');

        $result = $method->invoke($app, $claimScript, $envVars);

        // Verify that the actual command does NOT contain any of the sensitive secrets
        $this->assertStringNotContainsString('sensitive-token-here', $result);
        $this->assertStringNotContainsString('db-password-here', $result);

        // Verify it sets up the secure stdin redirection and sourcing logic
        $this->assertStringContainsString('umask 077', $result);
        $this->assertStringContainsString('cat > /tmp/.claw_env', $result);
        $this->assertStringContainsString('. /tmp/.claw_env', $result);
        $this->assertStringContainsString('rm -f /tmp/.claw_env', $result);
        $this->assertStringContainsString($claimScript, $result);
    }

    public function test_mcp_knob_resolves_through_instance_then_store_app(): void
    {
        $app = new PolydockAmazeeClawAiApp('Test App', 'Description', 'Author', 'https://example.com', 'support@example.com');

        // Unset anywhere: off.
        self::assertFalse($app->resolveMcpServerEnabled($this->createAppInstance()));

        // Store app turns it on for every instance of the app.
        self::assertTrue($app->resolveMcpServerEnabled($this->createAppInstance([
            'app_config' => ['mcp_enabled' => 'on'],
        ])));

        // An instance can turn it back off. This is why the knob stores
        // 'on'/'off' instead of a boolean: an empty value means "inherit".
        self::assertFalse($app->resolveMcpServerEnabled($this->createAppInstance([
            'app_config' => ['mcp_enabled' => 'on'],
            'data' => ['instance_config_mcp_enabled' => 'off'],
        ])));
    }

    public function test_enabling_mcp_issues_one_token_and_injects_it(): void
    {
        $app = new TestablePolydockAmazeeClawAiApp('Test App', 'Description', 'Author', 'https://example.com', 'support@example.com');
        $instance = $this->createAppInstance(['app_config' => ['mcp_enabled' => 'on']]);

        $app->callEnsureMcpServerConfiguration($instance);
        $token = $instance->getKeyValue(TestablePolydockAmazeeClawAiApp::MCP_TOKEN_KEY);

        self::assertNotSame('', $token);
        self::assertSame($token, $app->injectedVariables['OPENCLAW_MCP_TOKEN'] ?? null);

        // Post-create and claim both call this; the consumer's token must not
        // rotate under them on the second pass.
        $app->callEnsureMcpServerConfiguration($instance);
        self::assertSame($token, $instance->getKeyValue(TestablePolydockAmazeeClawAiApp::MCP_TOKEN_KEY));
        self::assertSame($token, $app->injectedVariables['OPENCLAW_MCP_TOKEN']);
    }

    public function test_disabling_mcp_removes_the_variable_only_when_one_was_issued(): void
    {
        $app = new TestablePolydockAmazeeClawAiApp('Test App', 'Description', 'Author', 'https://example.com', 'support@example.com');

        // Never enabled: don't spend a Lagoon call per instance per deploy.
        $untouched = $this->createAppInstance();
        $app->callEnsureMcpServerConfiguration($untouched);
        self::assertSame([], $app->deletedVariables);
        self::assertSame([], $app->injectedVariables);

        // Turned off after having been on: the endpoint has to go away.
        $wasOn = $this->createAppInstance([
            'data' => [TestablePolydockAmazeeClawAiApp::MCP_TOKEN_KEY => 'an-existing-token'],
        ]);
        $app->callEnsureMcpServerConfiguration($wasOn);
        self::assertSame(['OPENCLAW_MCP_TOKEN'], $app->deletedVariables);
        self::assertSame('', $wasOn->getKeyValue(TestablePolydockAmazeeClawAiApp::MCP_TOKEN_KEY));
    }

    public function test_a_failed_revocation_keeps_the_token_so_the_next_run_retries(): void
    {
        $app = new TestablePolydockAmazeeClawAiApp('Test App', 'Description', 'Author', 'https://example.com', 'support@example.com');
        $app->deleteSucceeds = false;

        $instance = $this->createAppInstance([
            'data' => [TestablePolydockAmazeeClawAiApp::MCP_TOKEN_KEY => 'an-existing-token'],
        ]);

        // Lagoon refused: the variable is still out there granting access, so the
        // stored token has to survive as the record that it needs removing.
        $app->callEnsureMcpServerConfiguration($instance);
        self::assertSame('an-existing-token', $instance->getKeyValue(TestablePolydockAmazeeClawAiApp::MCP_TOKEN_KEY));

        // Next lifecycle run retries instead of taking the "never enabled" path.
        $app->deleteSucceeds = true;
        $app->callEnsureMcpServerConfiguration($instance);
        self::assertSame(['OPENCLAW_MCP_TOKEN', 'OPENCLAW_MCP_TOKEN'], $app->deletedVariables);
        self::assertSame('', $instance->getKeyValue(TestablePolydockAmazeeClawAiApp::MCP_TOKEN_KEY));
    }
}
